# Generated by Django 3.1 on 2020-08-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
    ]
